# Generated by Django 4.2.17 on 2025-01-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistroy',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Accepedt', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='transactionhistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management_app.transactionhistroy'),
        ),
    ]
