# Generated by Django 4.2.17 on 2025-01-13 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0004_alter_transactionhistroy_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistroy',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('direct cash', 'Direct Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistroy',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='School_transaction_History', to=settings.AUTH_USER_MODEL),
        ),
    ]
