# Generated by Django 5.1.4 on 2024-12-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
