# Generated by Django 4.2.17 on 2025-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0005_transactionhistroy_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerreport',
            old_name='reason',
            new_name='instructor_reason',
        ),
        migrations.AddField(
            model_name='learnerreport',
            name='learner_reason',
            field=models.CharField(blank=True, choices=[('instructor-communication', 'Instructor Communication'), ('punctuality-and-availability', 'Punctuality and Availability'), ('teaching-style', 'Teaching Style'), ('professionalism', 'Professionalism'), ('comfort-level-with-instructor', 'Comfort Level with Instructor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learnerreport',
            name='reported_by',
            field=models.CharField(choices=[('learner', 'Learner'), ('school', 'School')], default='learner', max_length=10),
        ),
    ]
