# Generated by Django 4.2.17 on 2024-12-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0005_user_address'),
        ('user_management_app', '0006_usernotification'),
    ]

    operations = [
    ]
