# Generated by Django 4.2.17 on 2025-01-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0006_rename_reason_learnerreport_instructor_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerreport',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerreport_instructor', to=settings.AUTH_USER_MODEL, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='learnerreport',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerreport_learner', to=settings.AUTH_USER_MODEL, verbose_name='learner'),
        ),
    ]
