# Generated by Django 5.1.2 on 2024-12-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0007_merge_0005_user_address_0006_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Owner Admin'), ('learner', 'Learner'), ('instructor', 'Instructor'), ('school', 'School')], max_length=255),
        ),
    ]
