# Generated by Django 4.2.17 on 2025-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0009_referral_referral_count_referral_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletd_reason',
            field=models.CharField(blank=True, choices=[('duplicate', 'Duplicate'), ('inappropriate', 'Inappropriate'), ('spam', 'Spam'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
