# Generated by Django 4.2.17 on 2025-02-11 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0010_selectedsubscriptionpackagepaln_stripe_secret_id_and_more'),
        ('user_management_app', '0010_user_deletd_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('discount_price', models.FloatField(blank=True, default=1, help_text='Discount Price', null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('expiration_time', models.PositiveIntegerField(default=24, help_text='Coupon validity in hours')),
                ('calling_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_buyer_user', to=settings.AUTH_USER_MODEL, verbose_name='Calling Agent')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_offer_business', to='course_management_app.selectedsubscriptionpackagepaln', verbose_name='Business')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_offer_user', to=settings.AUTH_USER_MODEL, verbose_name='school')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
