# Generated by Django 5.1.2 on 2024-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0011_learnerreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='noti_type',
            field=models.CharField(choices=[('general', 'General')], max_length=255),
        ),
    ]
