# Generated by Django 4.2.17 on 2025-02-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0011_rename_stripe_secret_id_selectedsubscriptionpackagepaln_stripe_secret_id'),
        ('user_management_app', '0011_discountcoupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupons',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, help_text='Discount Price', null=True),
        ),
        migrations.AlterField(
            model_name='discountcoupons',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscribed_Package', to='course_management_app.selectedsubscriptionpackagepaln', verbose_name='Selected Subscription'),
        ),
    ]
