# Generated by Django 5.1.2 on 2024-12-26 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0013_user_lat_user_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='learner',
            field=models.ManyToManyField(blank=True, related_name='School_learner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='School_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
