# Generated by Django 5.1.2 on 2025-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0014_alter_discountcoupons_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='institute_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='registration_file',
            field=models.FileField(blank=True, null=True, upload_to='media/school/registration_file'),
        ),
    ]
