# Generated by Django 5.1.2 on 2025-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0015_alter_schoolprofile_institute_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='description',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=255, null=True),
        ),
    ]
