# Generated by Django 5.1.2 on 2025-07-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0016_remove_usernotification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
