# Generated by Django 5.1.2 on 2025-07-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0017_usernotification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistroy',
            name='transaction_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('Accepedt', 'Accepted'), ('rejected', 'Rejected')], max_length=15, null=True),
        ),
    ]
