# Generated by Django 5.1.2 on 2025-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0018_alter_transactionhistroy_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='learner_code',
            field=models.SlugField(blank=True, help_text='This code is for learner', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='total_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='unique_code',
            field=models.SlugField(blank=True, help_text='This code is for institute', null=True, unique=True),
        ),
    ]
