# Generated by Django 5.1.2 on 2025-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0019_referral_learner_code_alter_referral_total_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_progress',
            field=models.CharField(blank=True, choices=[('25', '25'), ('50', '50'), ('75', '75'), ('100', '100'), ('done', 'Done')], default='25', max_length=255, null=True),
        ),
    ]
