# Generated by Django 5.1.2 on 2025-07-14 16:16

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0020_user_course_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firt_time',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserNotificationsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('is_lesson_reminder1', models.BooleanField(default=True, help_text='One day before notification check')),
                ('is_lesson_reminder2', models.BooleanField(default=True, help_text='5 minutes before notification check')),
                ('is_course_progress', models.BooleanField(default=True)),
                ('is_profile_complete', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usernotificaation_notitype_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
