# Generated by Django 5.1.2 on 2025-07-07 18:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils_app', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='radius',
            name='current_location_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=9, null=True),
        ),
    ]
