# Generated by Django 5.1.2 on 2024-11-26 03:19

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the course', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the course')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the course in USD', max_digits=10)),
                ('license_category', models.CharField(help_text='Category of the license, e.g., Professional, Educational', max_length=100)),
                ('services', models.TextField(blank=True, help_text='List of services included in the course', null=True)),
                ('lesson_numbers', models.PositiveIntegerField(help_text='Number of lessons in the course')),
                ('refund_policy', models.TextField(blank=True, help_text='Details of the refund policy', null=True)),
                ('course_cover_image', models.ImageField(blank=True, help_text='Cover image for the course', null=True, upload_to='course_images/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Vehicle Name')),
                ('trainer_name', models.CharField(max_length=255, verbose_name='Trainer Name')),
                ('vehicle_registration_no', models.CharField(max_length=100, unique=True, verbose_name='Registration Number')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='License Number')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Vehicle Model')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/', verbose_name='Vehicle Image')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
