# Generated by Django 5.1.2 on 2024-12-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='license_category',
            field=models.ManyToManyField(blank=True, related_name='course_license_category', to='course_management_app.licensecategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='course_services', to='course_management_app.service'),
        ),
    ]
