# Generated by Django 4.2.17 on 2025-01-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0003_generalpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_service', to='course_management_app.service'),
            preserve_default=False,
        ),
    ]
