# Generated by Django 4.2.17 on 2025-01-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0004_course_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='service',
        ),
        migrations.AddField(
            model_name='course',
            name='service',
            field=models.ManyToManyField(default=None, related_name='course_service', to='course_management_app.service'),
        ),
    ]
