# Generated by Django 5.1.2 on 2024-12-05 06:52

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0004_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('offer_type', models.CharField(choices=[('flat_discount', 'Flat Discount'), ('percentage_discount', 'Percentage Discount'), ('custom_offer', 'Custom Offer')], max_length=255, verbose_name='Package Name')),
                ('name', models.CharField(max_length=255, verbose_name='Package Name')),
                ('audience', models.CharField(choices=[('new_user', 'New User'), ('old_user', 'Old User'), ('loyal_user', 'Loyal User'), ('referral_user', 'Referral User'), ('all_users', 'All Users')], max_length=255, verbose_name='Package Name')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount & offers(%)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management_app.course')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Package Name')),
                ('price', models.FloatField(default=0.0, verbose_name='Package Price')),
                ('total_course_hour', models.CharField(max_length=255, verbose_name='Total Course Hour')),
                ('lesson_numbers', models.PositiveIntegerField(verbose_name='Lesson Number')),
                ('free_pickup', models.FloatField(default=0.0, verbose_name='Free Pickup')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, related_name='package_services', to='course_management_app.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
