# Generated by Django 4.2.17 on 2024-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0005_discountoffer_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='booking_status',
            field=models.CharField(choices=[('free', 'Free'), ('booked', 'Booked')], default='free', max_length=10, verbose_name='Vehcile Status'),
        ),
    ]
