# Generated by Django 4.2.17 on 2025-01-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0007_lesson_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectedcourses',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='course_management_app.course'),
        ),
    ]
