# Generated by Django 4.2.17 on 2024-12-12 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management_app', '0007_usercourseprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCourseProfile',
            new_name='UserSelectedCourses',
        ),
    ]
