# Generated by Django 4.2.17 on 2024-12-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0006_certificate'),
        ('course_management_app', '0009_subscriptionpackageplan_and_more'),
    ]

    operations = [
    ]
