# Generated by Django 5.1.4 on 2024-12-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0006_certificate'),
        ('course_management_app', '0009_subscriptionpackageplan_and_more'),
    ]

    operations = [
    ]
