# Generated by Django 4.2.17 on 2025-02-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0010_selectedsubscriptionpackagepaln_stripe_secret_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedsubscriptionpackagepaln',
            old_name='Stripe_secret_id',
            new_name='stripe_secret_id',
        ),
    ]
