# Generated by Django 5.1.2 on 2025-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0011_rename_stripe_secret_id_selectedsubscriptionpackagepaln_stripe_secret_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
