# Generated by Django 4.2.17 on 2024-12-19 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management_app', '0011_alter_certificate_created_by_alter_course_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_vehicle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle', to=settings.AUTH_USER_MODEL),
        ),
    ]
