
# Generated by Django 5.1.2 on 2025-07-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0012_course_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hire_car_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hire car price'),
        ),
    ]
