# Generated by Django 5.1.2 on 2024-12-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0014_learnerselectedpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
