# Generated by Django 5.1.2 on 2025-01-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0014_remove_course_course_cover_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
