# Generated by Django 5.1.2 on 2024-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0015_alter_course_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerselectedpackage',
            name='courese_status',
            field=models.CharField(choices=[('on-going', 'On Going'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='on-going', max_length=255),
        ),
    ]
