# Generated by Django 5.1.2 on 2024-12-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0016_learnerselectedpackage_courese_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerselectedpackage',
            old_name='learner_selected_package',
            new_name='attended_lesson',
        ),
    ]
