# Generated by Django 5.1.2 on 2025-01-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0017_rename_learner_selected_package_learnerselectedpackage_attended_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerselectedpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerselectedpackage_package', to='course_management_app.package'),
        ),
    ]
