# Generated by Django 4.2.17 on 2025-01-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0016_remove_course_course_cover_image_and_more'),
        ('course_management_app', '0018_alter_learnerselectedpackage_package'),
    ]

    operations = [
    ]
