# Generated by Django 4.2.17 on 2025-01-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0020_courserating_courese_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserating',
            name='courese_status',
        ),
    ]
