# Generated by Django 5.1.2 on 2025-01-02 16:48

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerBookingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date', models.DateField()),
                ('road_test', models.BooleanField(default=False)),
                ('special_lesson', models.BooleanField(default=False)),
                ('hire_car', models.BooleanField(default=False)),
                ('slot', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('launch_break_start', models.TimeField(blank=True, null=True)),
                ('launch_break_end', models.TimeField(blank=True, null=True)),
                ('extra_space_start', models.TimeField(blank=True, null=True)),
                ('extra_space_end', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
