# Generated by Django 4.2.17 on 2024-12-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='location',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
