# Generated by Django 5.1.2 on 2025-01-02 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management_app', '0002_initial'),
        ('timing_slot_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerweekly_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerboked_vehicle', to='course_management_app.vehicle'),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyschedule_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyschedule_vehicle', to='course_management_app.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='learnerbookingschedule',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyschedule',
            unique_together={('user', 'date')},
        ),
    ]
