# Generated by Django 4.2.17 on 2024-12-26 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management_app', '0012_vehicle_instructor_alter_vehicle_user'),
        ('timing_slot_app', '0002_monthlyschedule_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyschedule',
            name='location',
        ),
        migrations.CreateModel(
            name='LearnerBookingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lesson_slection', models.CharField(blank=True, choices=[('i need a special lesson', 'I Need a special lesson'), ('i want to hire a car', 'I want to hire a car')], max_length=50, null=True, verbose_name='Lesson Selection')),
                ('date', models.DateField()),
                ('road_test', models.BooleanField(default=False)),
                ('slot', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerweekly_user', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerboked_vehicle', to='course_management_app.vehicle')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
