# Generated by Django 5.1.2 on 2025-01-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='lesson_duration',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Lesson duration in hours', null=True),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='lesson_gap',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Lesson gap in minutes', null=True),
        ),
    ]
