# Generated by Django 5.1.2 on 2025-01-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0003_remove_monthlyschedule_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerbookingschedule',
            name='lesson_slection',
            field=models.CharField(blank=True, choices=[('special_lesson', 'I Need a special lesson'), ('hire_car', 'I want to hire a car')], max_length=50, null=True, verbose_name='Lesson Selection'),
        ),
    ]
