# Generated by Django 5.1.2 on 2025-01-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0004_monthlyschedule_shift_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='operation_hour',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Operation time in hours', null=True),
        ),
    ]
