# Generated by Django 5.1.2 on 2025-01-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0004_alter_learnerbookingschedule_lesson_slection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerbookingschedule',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
