# Generated by Django 4.2.17 on 2025-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0005_monthlyschedule_operation_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='hire_car_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='hire_car_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='road_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
