# Generated by Django 4.2.17 on 2025-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0006_learnerbookingschedule_hire_car_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='road_test_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
