# Generated by Django 4.2.17 on 2025-01-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0007_learnerbookingschedule_road_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
