# Generated by Django 4.2.17 on 2025-01-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0009_learnerbookingschedule_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='hire_car_price_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='hire_car_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
