# Generated by Django 4.2.17 on 2025-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0010_learnerbookingschedule_hire_car_price_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerbookingschedule',
            name='road_test_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
