# Generated by Django 5.1.2 on 2025-06-19 13:44

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0011_rename_stripe_secret_id_selectedsubscriptionpackagepaln_stripe_secret_id'),
        ('timing_slot_app', '0011_learnerbookingschedule_road_test_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('road_test', models.BooleanField(default=False)),
                ('road_test_date', models.DateField(blank=True, null=True)),
                ('road_test_time', models.TimeField(blank=True, null=True)),
                ('road_test_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('special_lesson', models.BooleanField(default=False)),
                ('hire_car', models.BooleanField(default=False)),
                ('hire_car_status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('hire_car_price_paid', models.BooleanField(default=False)),
                ('hire_car_date', models.DateField(blank=True, null=True)),
                ('hire_car_time', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialllesson_user', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialllesson_vehicle', to='course_management_app.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
