# Generated by Django 5.1.2 on 2025-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0012_speciallesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallesson',
            name='hire_car_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
