# Generated by Django 5.1.2 on 2025-06-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0013_speciallesson_hire_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciallesson',
            name='road_test_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
