# Generated by Django 5.1.2 on 2025-06-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0014_alter_speciallesson_road_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciallesson',
            name='hire_car_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], max_length=20, null=True),
        ),
    ]
