# Generated by Django 5.1.2 on 2025-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0015_alter_speciallesson_hire_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerbookingschedule',
            name='hire_car_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='speciallesson',
            name='hire_car_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], max_length=20, null=True),
        ),
    ]
