# Generated by Django 5.1.2 on 2025-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing_slot_app', '0016_alter_learnerbookingschedule_hire_car_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerbookingschedule',
            name='lesson_name',
            field=models.TextField(blank=True, default='Lesson name', null=True),
        ),
    ]
